seed_everything: 42
trainer:
  logger:
  - class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      offline: false
      project: CMeEEner
      log_model: false
      prefix: ''
  checkpoint_callback: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.EarlyStopping
    init_args:
      monitor: val_loss
      min_delta: 0.0
      patience: 100
      verbose: true
      mode: min
      strict: true
      check_finite: true
      check_on_train_epoch_end: false
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args:
      logging_interval: step
      log_momentum: false
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      filename: '{epoch}-{val_loss:.2f}-{val_acc:.2f}'
      monitor: val_loss
      verbose: true
      save_last: true
      save_top_k: 2
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
  default_root_dir: null
  gradient_clip_val: 0.5
  gradient_clip_algorithm: value
  process_position: 0
  num_nodes: 1
  num_processes: 1
  devices: null
  gpus:
  - 0
  - 1
  auto_select_gpus: true
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 10
  fast_dev_run: false
  accumulate_grad_batches: 2
  max_epochs: 8000
  min_epochs: null
  max_steps: null
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0
  flush_logs_every_n_steps: 100
  log_every_n_steps: 1
  accelerator: ddp2
  sync_batchnorm: false
  precision: 16
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  truncated_bptt_steps: null
  resume_from_checkpoint: /data_200t/chenyaozu/39longformer/CMeEEner/3j3n1wej/checkpoints/epoch=360-val_loss=0.19-val_acc=0.78.ckpt
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  reload_dataloaders_every_epoch: false
  auto_lr_find: true
  replace_sampler_ddp: true
  terminate_on_nan: false
  auto_scale_batch_size: binsearch
  prepare_data_per_node: true
  plugins: ddp_sharded
  amp_backend: native
  amp_level: O2
  distributed_backend: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
model:
  max_seq_len: 128
  force_len: false
  model_len: 128
  learning_rate: 0.0003
  depth: 6
  mlp_depth: 1
  mlp_dim: 256
  configure_optimizers: CosineAnnealingWarmRestarts
  optimizer_name: AdamW
  from_pretrained: /data_200t/chenyaozu/data/base_model/chinese_roberta_L-2_H-128
  model: roberta
  bilstm: true
  performer_dim: 512
  pretrainedLayers:
  - 1
  - 3
  - 9
  - 11
  acc: true
  hidden_size: 256
  heads: 8
  num_labels: 28
  frequency: 1
  patience: 10
  dropout: 0.3
  interval: epoch
  T_max: 5
  trainfile: ./data/CMeEE/train.pk
  valfile: ./data/CMeEE/val.pk
  testfile: ./data/CMeEE/test.pk
  labelsfile: ./data/CMeEE/labels.pk
  batch_size: 256
  num_workers: 24
  bert: false
  useBertTokenizer: false
  init_decay_epochs: 60
  restart_interval: 5
  warmup_epochs: 30
  warmup_start_lr:
  - 5.0e-05
  - 2.0e-05
  - 5.0e-05
  min_decay_lr:
  - 2.0e-08
  - 2.0e-08
  - 5.0e-08
  restart_lr:
  - 1.0e-05
  - 1.0e-05
  - 3.0e-05
  attention_mask: true
  performerPlus: false
  warmup_steps: 100
  softmax_loss: false
  decode: crf
